config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/home'
  resources :opinions
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :followings, only: %i[create destroy]
  root 'users#home'
  get 'users/show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :follower_id, presence: true
  validates :followed_id, presence: true

  scope :can_follow, ->(user) { where.not(follower_id: user.id) }
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  validates :opinion, presence: true, length: { maximum: 280 }
  belongs_to :author, class_name: 'User', foreign_key: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, length: { minimum: 4, maximum: 20 }
  validates :fullname, presence: true, length: { minimum: 6, maximum: 80 }

  has_one_attached :photo
  has_one_attached :cover_image

  has_many :opinions, dependent: :destroy
  has_many :active_followings, class_name: 'Following', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_followings, class_name: 'Following', foreign_key: 'followed_id', dependent: :destroy

  has_many :following, through: :active_followings, source: :followed
  has_many :followers, through: :passive_followings, source: :follower

  def follow(user)
    active_followings.create(followed_id: user.id)
  end

  def unfollow(user)
    active_followings.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    following.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user

  def create
    current_user.follow(@user)
    redirect_to root_path
  end

  def destroy
    current_user.unfollow(@user)
    redirect_to @user
  end

  private

  def find_user
    @user = User.find_by_id(params[:user_id])
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :set_opinion, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /opinions or /opinions.json
  def index
    @opinions = Opinion.all
  end

  # POST /opinions or /opinions.json
  def create
    @opinion = current_user.opinions.build(opinion_params)
    @opinion.save
    redirect_to root_path
  end

  private

  # Only allow a list of trusted parameters through.
  def opinion_params
    params.require(:opinion).permit(:opinion)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:username, :fullname, :email, :password, :password_confirmation, :photo,
                                 :cover_image)
  end

  def account_update_params
    params.require(:user).permit(:username, :fullname, :email, :password, :password_confirmation, :current_password,
                                 :photo, :cover_image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def home
    @user = current_user
    @following = @user.following
    @followers = @user.followers
    @opinion = @user.opinions.new
    @opinions = Opinion.all.includes(:author)
    @users = User.all
  end

  def show
    @user = current_user
    @following = @user.following
    @followers = @user.followers
    @opinion = @user.opinions.new
    @opinions = Opinion.all.includes(:author)
    @user_opinions = @user.opinions.all.includes(:author)
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_notice(notice, alert)
    html = ''
    html += "<div class='notice'><p>#{notice}</p></div>" if notice.present?
    html += "<div class='alert'><p>#{alert}</p></div>" if notice.present?
    html.html_safe
  end

  def at_name(user)
    "@#{user.username.downcase}"
  end
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def can_follows(user, users)
    safe_join(
      users.filter { |u| u.id != user.id && !user.following?(u) }.map { |u| render 'follow_form', user: u }
    )
  end

  def user_followers(users)
    safe_join(
      users.map { |u| render 'profile', user: u }
    )
  end

  def render_user_opinions(opinions)
    safe_join(
      opinions.map { |opinion| render 'opinions/opinion', opinion: opinion }
    )
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
  crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <title>Capstone</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
  <body>
    <%= show_notice(notice, alert) %>
    <%= yield %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script> 
  </body>
</html>

app/views/opinions/_form.html.erb
<%= form_with(model: opinion) do |form| %>
  <% if opinion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(opinion.errors.count, "error") %> prohibited this opinion from being saved:</h2>

      <ul>
        <% opinion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :opinion %>
    <%= form.text_area :opinion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/opinions/_opinion.html.erb
<div class="opinion-wrap d-flex">
  <div class="profile-pic"><%= image_tag(opinion.author.photo) %></div>
  <div class="name-opinion-wrap flex-1">
    <div class="author-name"><%= opinion.author.fullname %> </div>
    <div class="opinion"><%= opinion.opinion %></div>
  </div>
</div>

app/views/opinions/edit.html.erb
<h1>Editing Opinion</h1>

<%= render 'form', opinion: @opinion %>

<%= link_to 'Show', @opinion %> |
<%= link_to 'Back', opinions_path %>

app/views/opinions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Opinions</h1>

<table>
  <thead>
    <tr>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @opinions.each do |opinion| %>
      <tr>
        <td><%= opinion.opinion %></td>
        <td><%= link_to 'Show', opinion %></td>
        <td><%= link_to 'Edit', edit_opinion_path(opinion) %></td>
        <td><%= link_to 'Destroy', opinion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Opinion', new_opinion_path %>

app/views/opinions/new.html.erb
<h1>New Opinion</h1>

<%= render 'form', opinion: @opinion %>

<%= link_to 'Back', opinions_path %>

app/views/opinions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Opinion:</strong>
  <%= @opinion.opinion %>
</p>

<%= link_to 'Edit', edit_opinion_path(@opinion) %> |
<%= link_to 'Back', opinions_path %>

app/views/users/_follow_form.erb
<%= form_with(url: followings_path, method: :post) do |form| %>
  <%= form.hidden_field :user_id, value: user.id %>
  <div class="d-flex align-items-center mb-2 follow-wrap">
    <div class="profile-pic rect lg me-3"><%= image_tag(user.photo) %></div>
    <div class="flex-1">
      <div class="name-button-wrap d-flex">
        <div class="me-3"><%= user.fullname %></div>
        <%= form.submit '+', class: 'follow-btn' %>
      </div>
      <div><%= at_name user %></div>
    </div>
  </div>
<% end %>

app/views/users/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light ">
    <div class="container-fluid ">
      <a class="navbar-brand" href="#"><%= image_tag("logos/book2.png", width: "40px")%></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0"></ul>
         
          
          <ul class="navbar-nav  d-flex align-items-center mr-3">
          
          <li class="nav-item m-1 mr-3 ml-3">
          <i class="fa fa-pencil" aria-hidden="true"></i>
          </li>
          <li class="nav-item m-1 mr-3 ml-3">
          <i class="fa fa-envelope-o" aria-hidden="true"></i>
          </li>
          <li class="nav-item m-1 mr-3 ml-3">
          <i class="fa fa-search" aria-hidden="true"></i>
          </li>
          <li class="nav-item m-1 mr-3 ml-3">
          <i class="fa fa-cog" aria-hidden="true"></i>
          </li>
        </ul>
        
      </div>
    </div>
  </nav>

app/views/users/_profile.html.erb
<div class="d-flex align-items-center p-3">
  <div class="profile-pic">
  <%= image_tag(user.photo)  %>
  </div>
  <div class="name-wrap ms-3">
    <div class="full-name"><%= user.fullname %></div>
    <div class="at-name"><%= at_name user %></div>
  </div>
</div>

app/views/users/_sidebar.html.erb
<div class="bg-dark text-light flex-1 h-100">
  <%= render 'profile', user: @user %>
  
  <div class="d-flex text-center follow-count">
  <div class="flex-1 cell">
      <div><%= @following.length %></div>
      <div>FOLLOWING</div>
    </div>
    <div class="flex-1 cell">
      <div><%= @followers.length %></div>
      <div>FOLLOWERS</div>
    </div>
  </div>
  <ul class="aside-links">
    <li>
      <i class="fa fa-home" aria-hidden="true"></i>
      <%= link_to "Home", root_path, class: "aside-link home" %>
    </li>
    <li>
      <i class="fa fa-user" aria-hidden="true"></i>
      <%= link_to "Profile", users_show_path, class: "aside-link user" %>
    </li>
    <li>
      <i class="fa fa-home" aria-hidden="true"></i>
      <%=link_to 'Logout', destroy_user_session_path, method: :delete, class: "aside-link logout" %>
    </li>
  </ul>
</div>

app/views/users/home.html.erb
<div class="container-fluid">
  <div class="row">
    <aside class="col-3 d-flex">
      <%= render partial: "users/sidebar", local: { following: @following, followers: @followers } %>
    </aside>
    <div class="col-9">
      <%= render "users/header" %>
      <div class="container-flex">
      
        <div class="row">
          <main class="col-8">
            <div class="opinion-form-wrap mt-sm">
              <h3>Opinion</h3>
              <%= form_with model: @opinion do |form| %>
                <%= form.text_field :opinion %>
              <% end %>
            </div>
            <div class="opinions-list bg-light p3">
              <h3 class="opinions-header h4">Recent Opinions</h3>
              <%= render @opinions %> 
            </div>
          </main>
          <aside class="col-4 h-100">
            <h3 class="mt-3 h4">Who To Follow</h3>
            <div>
              <%= can_follows(@user, @users) %>
            </div>
          </aside>
        </div>
      </div>
      <footer></footer>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <aside class="col-3 d-flex">
      <%= render partial: "users/sidebar", local: { following: @following, followers: @followers } %>
    </aside>
    <div class="col-9">
      <%= render "users/header" %>
      <div class="container-flex">
        <div class="row">
          <main class="col-8">
            <div class="cover-picture-wrap">
             <%= image_tag(@user.cover_image) %>
            </div>
            <div class="opinion-form-wrap">
              <h3>Opinion</h3>
              <%= form_with model: @opinion do |form| %>
                <%= form.text_field :opinion %>
              <% end %>
            </div>
            <div class="opinions-list bg-light p3">
              <h3 class="opinions-header h4">Recent Opinions</h3>
              <%= render_user_opinions @user_opinions %>
            </div>
          </main>
          <aside class="col-4 h-100">
            <div class="text-align-center p-3">
              <div class="d-flex justify-content-center"><div class="profile-pic xlg"><%= image_tag(current_user.photo) %></div></div>
              <div class="name-wrap">
                <div class="full-name"><%= @user.fullname %></div>
                <div class="at-name"><%= at_name @user %></div>
              </div>
            </div>
            <div class="d-flex text-center follow-count sm">
              <div class="flex-1 cell">
                <div><%= @user_opinions.length %></div>
                <div class="label">OPINIONS</div>
              </div>
              <div class="flex-1 cell">
                <div><%= @following.length %></div>
                <div class="label">FOLLOWING</div>
              </div>
              <div class="flex-1 cell">
                <div><%= @followers.length %></div>
                <div class="label">FOLLOWERS</div>
              </div>
            </div>
            <h3 class="mt-3 h4">Followers</h3>
            <div>
              <%= user_followers(@followers) %>
            </div>
          </aside>
        </div>
      </div>
      <footer></footer>
    </div>
  </div>
</div>